### ISSUE TITLE
Multilingual Capabilities

### ISSUE THREAD

**Issue by eschaffn** [SaadNoor555/Document-Layout-Analysis#2]
I've been able to use the 'e50.aug' model with pretty good success on most languages and scripts, including Chinese, Cyrillic and Latin scripts, but when swapping to the publaynet weights that you released the multilingual capabilities seem to deteriorate. Would you have any idea why, or how to fix? 

Also, do you think training with these datasets would work as multilingual for your model?

https://github.com/buptlihang/CDLA
https://github.com/doc-analysis/DocBank

Thank you

**Comment by SaadNoor555** [comment]
I am not quite sure why e50aug has better multilingual capabilities than the one trained only on publynet. A potential reason could be because the aug model has been exposed to augmented images so it does not rely on the texts themselves to make predictions, but then again it is just a guess.
And I am pretty certain that training with the datasets you mentioned will definitely improve the multilingual capabilities of the YOLO-based models.
